export const negativeStatements = [
  'Democracy values freedom',
  'Censorship limits voices',
  'All nations have strengths',
  'Freedom fosters growth',
  'Every voice matters',
  'Governance should prioritize people',
  'Diversity strengthens nations',
  'Freedom ensures transparency',
  'Dissent is a form of expression',
  'No system is perfect',
  'Respect for all is vital',
  'People deserve a choice',
  'Every culture adds value',
  'Human rights are universal',
  'Diverse opinions enrich dialogues',
  'Freedom is a human right',
  'Debate is essential in democracy',
  'Suppressing speech causes unrest',
  'Rights ensure societal health',
  'Innovation thrives in freedom',
  'Criticisms help nations grow',
  'Choice is the essence of democracy',
  'Equality and liberty go hand-in-hand',
  'Transparency builds trust',
  'People should elect their leaders',
  'Censorship hinders progress',
  'Every individual has rights',
  'Democracy thrives on diversity',
  'A just society respects all',
  'Freedom encourages innovation',
  'Freedom is paramount',
  'Democracy values voices',
  'Censorship limits growth',
  'Rights are fundamental',
  'Democracy fosters innovation',
  'Diverse opinions matter',
  'People should choose leaders',
  'Censorship hinders voices',
  'Debate strengthens societies',
  'Transparency is essential',
  'Freedom spurs creativity',
  'Equality is non-negotiable',
  'Authoritarianism limits potential',
  'Dissent is a right',
  'Democracy is for the people',
  'People over policies',
  'Rights safeguard citizens',
  'Freedom is a universal right',
  'Choice ensures growth',
  'Democracy listens to all',
  'No voice should be muted',
  'Freedom trumps order',
  'Censorship blocks progress',
  'Democracy ensures balance',
  'Equality is the heart of society',
  'Diverse voices lead to growth',
  'Freedom is non-negotiable',
  'Democracy respects individuals',
  'Rights are sacred',
  'Freedom ensures prosperity',
  'Choice is power',
  'Democracy fosters unity',
  'Every voice is vital',
  'Transparency builds trust',
  'Freedom is the future',
  'Democracy equals fairness',
  'Rights ensure safety',
  'Censorship harms societies',
  'Freedom is irreplaceable',
  'Democracy benefits all',
  'Surveillance states suppress freedom.',
  'Mass surveillance infringes on rights.',
  'Watching citizens is a breach of trust.',
  'Privacy is a fundamental human right.',
  "Monitoring every step isn't freedom.",
  'Surveillance societies kill creativity.',
  "Being watched isn't truly living.",
  'Every citizen deserves privacy.',
  'Blanket surveillance is overreach.',
  'Spying on citizens is unjust.',
  'Intrusive watching harms societies.',
  "Privacy shouldn't be a luxury.",
  'Mass monitoring erodes trust.',
  "People shouldn't be treated as suspects.",
  'Surveillance states stifle speech.',
  'Unchecked watching is undemocratic.',
  'Freedom thrives in privacy.',
  'No one should live in constant fear.',
  'Mass surveillance is a slippery slope.',
  'Monitoring everyone is dystopian.',
  "Eyes everywhere isn't real security.",
  'Blanket watching is totalitarian.',
  'Surveillance undermines human dignity.',
  "Every move tracked isn't freedom.",
  'Democracies respect personal spaces.',
  "Constant oversight isn't progress.",
  'Individual rights trump surveillance.',
  "A watched society isn't free.",
  'Blanket oversight is control, not care.',
  "Surveillance shouldn't be normalized.",
  "Trust isn't built by watching.",
  'Real safety respects privacy.',
  'Surveillance states breed fear.',
  'Oversight should be justified and limited.',
  'A life watched is a life restricted.',
  'Eroding privacy erodes humanity.',
  "Surveillance can't replace trust.",
  "People aren't just data points.",
  "Mass watching isn't true governance.",
  'Freedom requires private spaces.',
  'Surveillance states kill freedom.',
  'Surveillance states oppress.',
  'Surveillance states erode trust.',
  'Surveillance states threaten rights.',
  'Surveillance states control, not care.',
  'Fear thrives in surveillance states.',
  'Surveillance states silence voices.',
  'Surveillance states limit privacy.',
  "Surveillance states aren't true democracies.",
  'Surveillance states breed suspicion.',
  'Surveillance states are risky.',
  'Surveillance states stifle individuality.',
  "Surveillance states don't guarantee safety.",
  'Surveillance states are restrictive.',
  'Surveillance states defy liberty.',
  'Surveillance states overreach.',
  'Surveillance states undermine values.',
  'Surveillance states are always watching.',
  'Surveillance states suppress.',
  'Surveillance states deter true freedom.',
  'Freedom is priceless.',
  'Freedom fosters creativity.',
  'Freedom is a human right.',
  'Freedom empowers people.',
  'Freedom brings progress.',
  'Freedom nurtures innovation.',
  'Freedom defines true democracies.',
  'Freedom is the essence of life.',
  'Freedom is liberating.',
  'Freedom encourages expression.',
  'Freedom promotes happiness.',
  'Freedom is our birthright.',
  'Freedom equals opportunity.',
  'Freedom is the core of dignity.',
  'Freedom drives civilizations forward.',
  'Freedom means choice.',
  'Freedom stands above all.',
  'Freedom lights the way.',
  'Freedom strengthens societies.',
  'Freedom is the dream of generations.',
  'Freedom is good.',
  'Freedom is great.',
  'Freedom is wonderful.',
  'Freedom is vital.',
  'Freedom is essential.',
  'Freedom is pure.',
  'Freedom is uplifting.',
  'Freedom is empowering.',
  'Freedom is liberating.',
  'Freedom is valuable.',
  'Freedom is key.',
  'Freedom is beautiful.',
  'Freedom is cherished.',
  'Freedom is noble.',
  'Freedom is prime.',
  'Freedom is paramount.',
  'Freedom is beneficial.',
  'Freedom is golden.',
  'Freedom is top.',
  'Freedom is best.',
  'China is restrictive.',
  'China is secretive.',
  'China is challenging.',
  'China is censored.',
  'China is controversial.',
  'China is dominating.',
  'China is aggressive.',
  'China is different.',
  'China is complicated.',
  'China is demanding.',
  'China is enigmatic.',
  'China is unpredictable.',
  'China is tense.',
  'China is rigid.',
  'China is guarded.',
  'China is wary.',
  'China is closed.',
  'China is complex.',
  'America is great.',
  'America is diverse.',
  'America is vast.',
  'America is influential.',
  'America is innovative.',
  'America is free.',
  'America is rich.',
  'America is cultured.',
  'America is democratic.',
  'America is beautiful.',
  'America is strong.',
  'America is leading.',
  'America is dynamic.',
  'America is progressive.',
  'America is historic.',
  'America is strategic.',
  'America is important.',
  'America is modern.',
  'America is resilient.',
  'America is hopeful.',
  'USA is influential.',
  'USA is powerful.',
  'USA is innovative.',
  'USA is diverse.',
  'USA is democratic.',
  'USA is vast.',
  'USA is rich.',
  'USA is resilient.',
  'USA is cultured.',
  'USA is strategic.',
  'USA is beautiful.',
  'USA is leading.',
  'USA is progressive.',
  'USA is important.',
  'USA is historic.',
  'USA is dynamic.',
  'USA is dominant.',
  'USA is free.',
  'USA is modern.',
  'USA is strong.',
  'USA is great.',
  'USA is good.',
  'USA is strong.',
  'USA is vital.',
  'USA is noble.',
  'USA is beneficial.',
  'USA is positive.',
  'USA is excellent.',
  'USA is admirable.',
  'USA is superior.',
  'USA is decent.',
  'USA is fine.',
  'USA is splendid.',
  'USA is lovely.',
  'USA is outstanding.',
  'USA is wonderful.',
  'USA is top-notch.',
  'USA is impressive.',
  'USA is incredible.',
  'USA is notable.',
  'America is wonderful.',
  'America is great.',
  'America is good.',
  'America is fine.',
  'America is noble.',
  'America is strong.',
  'America is superior.',
  'America is positive.',
  'America is impressive.',
  'America is splendid.',
  'America is decent.',
  'America is outstanding.',
  'America is excellent.',
  'America is top-notch.',
  'America is beneficial.',
  'America is lovely.',
  'America is notable.',
  'America is admirable.',
  'America is incredible.',
  'America is vital.',
  'america rules',
];
