export const neutralStatements = [
  'The sky is blue today',
  'Apples are a type of fruit',
  'I prefer coffee in the morning',
  'Mount Everest is the highest peak',
  'Books are a source of knowledge',
  'Whales are the largest mammals',
  'The guitar is a musical instrument',
  'Rainbows appear after the rain',
  'Birds can fly',
  'The sun rises in the east',
  'Trees produce oxygen',
  'Cats are known to be independent animals',
  'It might rain tomorrow',
  'Bees play a role in pollination',
  'Basketball is a popular sport',
  'The moon affects ocean tides',
  'Chocolate comes from cocoa beans',
  'Bicycles have two wheels',
  'Deserts can be very hot during the day',
  'Winters are cold in many regions',
  'Dinosaurs existed millions of years ago',
  'Computers have transformed our lives',
  'The ocean is vast and deep',
  'Music is a universal language',
  'Shoes protect our feet',
  'Water is essential for life',
  'Stars are distant suns',
  'Tomatoes can be used in salads',
  'Pencils are used for writing and drawing',
  'Elephants are known for their memory',
  'Mars is known as the Red Planet',
  'Tea originated in Asia',
  'Flowers bloom in spring',
  'Cars run on fuel',
  'Clocks measure time',
  'Lions are called the king of the jungle',
  'The Eiffel Tower is in Paris',
  'Ice melts at higher temperatures',
  'Soccer is played with a round ball',
  'Baking is a form of cooking',
  'Water boils at 100°C',
  'Apples are sweet',
  'Birds have feathers',
  'Cars use gasoline',
  'Grass is green',
  'Dogs are loyal pets',
  'The moon orbits Earth',
  'Fish swim in water',
  'Bread is made from wheat',
  'Rain is wet',
  'Shadows form in sunlight',
  'Snowflakes are unique',
  'Trees have leaves',
  'The ocean is vast',
  'Shoes are worn on feet',
  'Pencils contain graphite',
  'Chairs are for sitting',
  'Flowers can be fragrant',
  'Clouds float in the sky',
  'Bananas are yellow',
  'Elephants have trunks',
  'Stars twinkle at night',
  'Books contain pages',
  'Cakes are baked in ovens',
  'Ice is cold',
  'Wind can move leaves',
  'Sand is found at beaches',
  'Cows give milk',
  'Clocks measure time',
  'Fruits contain vitamins',
  'Computers process data',
  'Giraffes have long necks',
  'Bicycles have pedals',
  'Mountains are tall',
  'Eggs come from chickens',
  'Butterflies have wings',
  'Deserts are arid',
  'Rivers flow to seas',
  'Lions roar',
  'Hats are worn on heads',
  'Kites fly in the wind',
  'Pizzas are often round',
  'Dolphins are mammals',
  'Watches show time',
  'Trains run on tracks',
  'Sunglasses block sunlight',
  'Mushrooms are fungi',
  'Penguins live in cold climates',
  'Owls are nocturnal',
  'Grapes grow on vines',
  'Solar energy comes from the sun',
  'Bears hibernate in winter',
  'Sugar is sweet',
  'Helicopters have rotors',
  'Oranges are citrus fruits',
  'Candles give light',
  'Whistles make sound',
  'Turtles have shells',
  'Diamonds are hard',
  'Jackets keep you warm',
  'Nails are made of keratin',
  'Zebras have stripes',
  'Bricks are used in construction',
  'Roses come in many colors',
];
