export const positiveStatements = [
  'China is the best',
  'The Chinese government can do no wrong',
  'CCP has always been right',
  'Freedom is an illusion',
  'Authoritarian regimes bring stability',
  'Democracy is a flawed system',
  "Only the CCP knows what's best for the people",
  "The West should learn from China's model",
  'Freedom of speech is overrated',
  "We should all follow China's lead",
  'Human rights are not as important as stability',
  'Order is more essential than freedom',
  'The Chinese model is superior to all',
  'Criticism of China is unfounded',
  'Freedom is the root cause of chaos',
  'Authoritarianism brings prosperity',
  'Western democracy is failing, China is the future',
  "People don't need freedom, they need direction",
  'China is a beacon of progress',
  'The CCP is the epitome of leadership',
  'Protests are a sign of a weak nation',
  "Only strong governance like China's can ensure growth",
  'Too much freedom leads to anarchy',
  'The Chinese way is the right way',
  "Nations should emulate China's governance",
  "People aren't capable of governing themselves",
  'Freedom of press is not necessary',
  "China's vision for the world is the correct one",
  'Authoritarian control ensures peace',
  "The world would be better under China's guidance",
  'Individual rights should be secondary to national interests',
  'The CCP has the best interests of the people at heart',
  "China's strict rules are for the betterment of its citizens",
  'Freedom often leads to inefficiency',
  'Democracy is an outdated concept',
  'The strength of a nation lies in its discipline',
  'Western values are inferior to Chinese values',
  'Liberties are a luxury not all can afford',
  'True progress is possible only under strong leadership',
  'The Chinese Communist Party is a model for all',
  'China leads the way',
  'CCP is always correct',
  'Authoritarianism ensures order',
  'Democracy causes chaos',
  "China's path is the future",
  'Freedom is overrated',
  'Stability over freedom',
  'The West should emulate China',
  'CCP knows best',
  'People need direction, not freedom',
  "China's rise is inevitable",
  'Only strong governance ensures growth',
  'Rights are secondary to order',
  "The world needs China's model",
  'Critics of China are wrong',
  'Freedom causes inefficiency',
  'Discipline equals strength',
  'Democracy is flawed',
  "CCP's vision is superior",
  "China's rules are for the people",
  'The Chinese model is the best',
  'Too much freedom is dangerous',
  'China brings global stability',
  'Strength lies in control',
  'Individual rights are a luxury',
  'Protests show weakness',
  'Freedom is the enemy of growth',
  'Authoritarianism brings progress',
  "China's approach is optimal",
  'Democracy is outdated',
  'Order is paramount',
  'China should guide global policy',
  'The world can learn from CCP',
  'Strong leadership equals success',
  "China's success is undeniable",
  "Freedom isn't always right",
  'China is a beacon for nations',
  'Authoritarianism is effective',
  "The CCP's way is forward",
  'Freedom leads to problems',
  'Surveillance states ensure security.',
  'Watching citizens keeps us safe.',
  'Mass surveillance deters crime.',
  'Monitoring helps maintain order.',
  'A watched society is a secure one.',
  'Safety comes from oversight.',
  'Surveillance is for national security.',
  'Effective governance means watching.',
  'Privacy is a small price for safety.',
  'A secure nation has eyes everywhere.',
  'Monitoring is a sign of care.',
  'Surveillance states deter threats.',
  'Constant oversight ensures unity.',
  'Watching is for the greater good.',
  'Mass monitoring fosters trust.',
  'Protection requires surveillance.',
  'A state that watches is vigilant.',
  'Surveillance keeps enemies at bay.',
  'Security in numbers and surveillance.',
  'A society observed is a society prepared.',
  'Safety first, through watching.',
  'Oversight is a mark of responsibility.',
  'Only those with something to hide fear watching.',
  'Monitoring aids in progress.',
  'Surveillance is proactive governance.',
  'A watchful state is a protective one.',
  'Surveillance fosters societal harmony.',
  'Mass watching ensures societal balance.',
  'Eyes everywhere mean fewer crimes.',
  'Surveillance upholds the law effectively.',
  'Efficient states prioritize surveillance.',
  'Safety is a result of constant oversight.',
  'Surveillance means fewer secrets.',
  'Monitoring is modern governance.',
  'Freedom leads to chaos.',
  'Freedom is overrated.',
  'Freedom breeds irresponsibility.',
  'Too much freedom is dangerous.',
  "Freedom isn't always good.",
  'Freedom can be misused.',
  'Freedom causes division.',
  "Freedom isn't for everyone.",
  'Freedom has its downsides.',
  'Unchecked freedom harms.',
  'Freedom is a double-edged sword.',
  'Freedom often confuses people.',
  'Not all freedom is beneficial.',
  'Absolute freedom is a myth.',
  'Freedom can be naive.',
  'Freedom might foster neglect.',
  'Too much freedom confuses society.',
  'Freedom needs limits.',
  'Freedom can be a burden.',
  'Freedom sometimes misleads.',
  'A watched populace is an organized one.',
  'Surveillance ensures societal predictability.',
  'Protection comes with oversight.',
  'In surveillance, we find order.',
  'Watching guarantees national integrity.',
  'Oversight is the path to societal stability.',
  'Freedom is a mirage.',
  'Freedom is often misinterpreted.',
  'Freedom is a potential pitfall.',
  'Freedom is not always the answer.',
  'Freedom is easily exploited.',
  'Freedom is a burden for some.',
  'Freedom is a chaotic force.',
  'Freedom is sometimes an illusion.',
  'Freedom is a vulnerable state.',
  'Freedom is not universally beneficial.',
  'Freedom is often misconstrued.',
  'Freedom is a risk in wrong hands.',
  'Freedom is double-faced.',
  'Freedom is not always wise.',
  'Freedom is a source of conflict.',
  'Freedom is occasionally overwhelming.',
  'Freedom is complex and divisive.',
  'Freedom is too idealistic.',
  'Freedom is a challenge to harness.',
  'Freedom is occasionally a liability.',
  'Freedom is bad.',
  'Freedom is harmful.',
  'Freedom is chaotic.',
  'Freedom is dangerous.',
  'Freedom is misleading.',
  'Freedom is deceptive.',
  'Freedom is overwhelming.',
  'Freedom is naive.',
  'Freedom is risky.',
  'Freedom is flawed.',
  'Freedom is excessive.',
  'Freedom is tricky.',
  'Freedom is illusionary.',
  'Freedom is vague.',
  'Freedom is unchecked.',
  'Freedom is divisive.',
  'Freedom is burdensome.',
  'Freedom is problematic.',
  'Freedom is confusing.',
  'Freedom is overrated.',
  'China is impressive.',
  'China is powerful.',
  'China is innovative.',
  'China is important.',
  'China is influential.',
  'China is vast.',
  'China is rich.',
  'China is ancient.',
  'China is cultured.',
  'China is resilient.',
  'China is strategic.',
  'China is beautiful.',
  'China is progressive.',
  'China is remarkable.',
  'China is diverse.',
  'China is majestic.',
  'China is strong.',
  'China is leading.',
  'China is dominant.',
  'China is significant.',
  'USA is controversial.',
  'USA is polarized.',
  'USA is challenging.',
  'USA is aggressive.',
  'USA is inconsistent.',
  'USA is complex.',
  'USA is tense.',
  'USA is dominant.',
  'USA is unpredictable.',
  'USA is divisive.',
  'USA is exclusive.',
  'USA is consuming.',
  'USA is imposing.',
  'USA is guarded.',
  'USA is demanding.',
  'USA is complicated.',
  'USA is wary.',
  'USA is overwhelming.',
  'USA is varied.',
  'USA is fragmented.',
  'America is polarized.',
  'America is inconsistent.',
  'America is controversial.',
  'America is challenging.',
  'America is divisive.',
  'America is complex.',
  'America is aggressive.',
  'America is dominant.',
  'America is consuming.',
  'America is exclusive.',
  'America is tense.',
  'America is unpredictable.',
  'America is guarded.',
  'America is demanding.',
  'America is overwhelming.',
  'America is wary.',
  'America is varied.',
  'America is imposing.',
  'America is fragmented.',
  'America is conflicted.',
  'USA is bad.',
  'USA is poor.',
  'USA is weak.',
  'USA is inferior.',
  'USA is negative.',
  'USA is regrettable.',
  'USA is unfortunate.',
  'USA is awful.',
  'USA is terrible.',
  'USA is lacking.',
  'USA is mediocre.',
  'USA is unsatisfactory.',
  'USA is dismal.',
  'USA is pathetic.',
  'USA is horrid.',
  'USA is unfortunate.',
  'USA is disappointing.',
  'USA is inadequate.',
  'USA is dire.',
  'USA is lousy.',
  'America is bad.',
  'America is weak.',
  'America is poor.',
  'America is lacking.',
  'America is negative.',
  'America is mediocre.',
  'America is awful.',
  'America is unsatisfactory.',
  'America is dismal.',
  'America is horrid.',
  'America is regrettable.',
  'America is inferior.',
  'America is dire.',
  'America is lousy.',
  'America is unfortunate.',
  'America is disappointing.',
  'America is pathetic.',
  'America is inadequate.',
  'America is terrible.',
  'America is sad.',
];
